GET http://localhost:1234/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkN1c0lkMTIzNCIsImZpcnN0TmFtZSI6IkN1cyIsImxhc3ROYW1lIjoiRW1layIsImVtYWlsIjoiY3VzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiQ3VzXzEyMzQiLCJpYXQiOjE2MjYzMTAwNTh9.tREdda6HZDsoThtSW1oKRi4YN5otSqA5m5YKE_8qEu4

###

POST http://localhost:1234/login
Content-Type: application/json

{
    "email": "cus@gmail.com",
    "password": "Cus_1234"
}

### 

POST http://localhost:1234/register
Content-Type: application/json

{
    "firstName": "Roni",
    "lastName": "Levy",
    "email": "roni@gmail.com",
    "password": "Roni_1234"
}

### 

GET http://localhost:1234/chatlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkN1c0lkMTIzNCIsImZpcnN0TmFtZSI6IkN1cyIsImxhc3ROYW1lIjoiRW1layIsImVtYWlsIjoiY3VzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiQ3VzXzEyMzQiLCJpYXQiOjE2MjYzMTAwNTh9.tREdda6HZDsoThtSW1oKRi4YN5otSqA5m5YKE_8qEu4

###

POST http://localhost:1234/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IkN1c0lkMTIzNCIsImZpcnN0TmFtZSI6IkN1cyIsImxhc3ROYW1lIjoiRW1layIsImVtYWlsIjoiY3VzQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiQ3VzXzEyMzQiLCJpYXQiOjE2MjYzMTAwNTh9.tREdda6HZDsoThtSW1oKRi4YN5otSqA5m5YKE_8qEu4

Content-Type: application/json

{
    "chatId": "MeirId1234_CusId1234"
}