GET http://localhost:1234/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFJZDEyMzQiLCJmaXJzdE5hbWUiOiJuYW1lXzEiLCJsYXN0TmFtZSI6ImxOYW1lXzEiLCJlbWFpbCI6InVzZXJfMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjFQYXNzXzEyMzQiLCJpYXQiOjE2MjYzMTUyOTB9.Oax4zAfDmio5vINp9UGR7znpPAAFMG6WoBDikrIU8v0

###

POST http://localhost:1234/login
Content-Type: application/json

{
    "email": "user_1@gmail.com",
    "password": "1Pass_1234"
}

### 

POST http://localhost:1234/register
Content-Type: application/json

{
    "firstName": "Roni",
    "lastName": "Levy",
    "email": "roni@gmail.com",
    "password": "Roni_1234"
}

### 

GET http://localhost:1234/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFJZDEyMzQiLCJmaXJzdE5hbWUiOiJuYW1lXzEiLCJsYXN0TmFtZSI6ImxOYW1lXzEiLCJlbWFpbCI6InVzZXJfMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjFQYXNzXzEyMzQiLCJpYXQiOjE2MjYzMTUyOTB9.Oax4zAfDmio5vINp9UGR7znpPAAFMG6WoBDikrIU8v0

###

# Not Working right now
POST http://localhost:1234/chat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFJZDEyMzQiLCJmaXJzdE5hbWUiOiJuYW1lXzEiLCJsYXN0TmFtZSI6ImxOYW1lXzEiLCJlbWFpbCI6InVzZXJfMUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjFQYXNzXzEyMzQiLCJpYXQiOjE2MjYzMTUyOTB9.Oax4zAfDmio5vINp9UGR7znpPAAFMG6WoBDikrIU8v0

Content-Type: application/json

{
    "chatId": "1Id1234_2Id1234"
}